{% set name = "perl-http-date" %}
{% set version = "6.02" %}
{% set sha256 = "e8b9941da0f9f0c9c01068401a5e81341f0e3707d1c754f8e11f42a7e629e333" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: HTTP-Date-6.02.tar.gz
  url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Date-6.02.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-time-local

  run:
    - perl
    #- perl-time-local

test:
  # Perl 'use' tests
  imports:
    - HTTP::Date

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/HTTP::Date
  license: perl_5
  summary: 'date conversion routines'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: HTTP::Date
  cpan_module: HTTP::Date

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
