{% set name = "perl-test-object" %}
{% set version = "0.08" %}
{% set sha256 = "65278964147837313f4108e55b59676e8a364d6edf01b3dc198aee894ab1d0bb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-Object-0.08.tar.gz
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Object-0.08.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-exporter
    #- perl-findbin
    #- perl-strict
    #- perl-test-builder-tester
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-overload
    #- perl-test-more
    #- perl-lib
    #- perl-scalar-util
    #- perl-vars
    #- perl-carp
    #- perl-warnings
    #- perl-file-spec-functions

  run:
    - perl
    #- perl-carp
    #- perl-overload
    #- perl-test-more
    #- perl-scalar-util
    #- perl-vars
    #- perl-strict
    #- perl-exporter

test:
  # Perl 'use' tests
  imports:
    - Test::Object
    - Test::Object::Test

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/karenetheridge/Test-Object
  license: perl_5
  summary: 'Thoroughly testing objects via registered handlers'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::Object
  cpan_module: Test::Object

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
