{% set name = "perl-file-listing" %}
{% set version = "6.04" %}
{% set sha256 = "1e0050fcd6789a2179ec0db282bf1e90fb92be35d1171588bd9c47d52d959cf5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: File-Listing-6.04.tar.gz
  url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/File-Listing-6.04.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-http-date
    #- perl-extutils-makemaker

  run:
    - perl
    - perl-http-date

test:
  # Perl 'use' tests
  imports:
    - File::Listing
    - File::Listing::apache
    - File::Listing::dosftp
    - File::Listing::netware
    - File::Listing::unix
    - File::Listing::vms

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/File::Listing
  license: perl_5
  summary: 'parse directory listing'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: File::Listing
  cpan_module: File::Listing

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
