{% set name = "perl-test-output" %}
{% set version = "1.031" %}
{% set sha256 = "f8b8f37185717872727d06f6c078fa77db794410faf2f6da4d37b0b7650f7ea4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-Output-1.031.tar.gz
  url: https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Test-Output-1.031.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-capture-tiny
    #- perl-file-temp
    #- perl-extutils-makemaker
    #- perl-test-tester
    #- perl-test-more
    #- perl-file-spec-functions

  run:
    - perl
    - perl-capture-tiny
    #- perl-file-temp

test:
  # Perl 'use' tests
  imports:
    - Test::Output

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/briandfoy/test-output
  license: perl_5
  summary: 'Utilities to test STDOUT and STDERR messages.'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::Output
  cpan_module: Test::Output

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
