{% set name = "perl-http-daemon" %}
{% set version = "6.05" %}
{% set sha256 = "b47fa46688bfd8a6e99eccf449dc5705e5530022b2fc8a873a9d07921345c72d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: HTTP-Daemon-6.05.tar.gz
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/HTTP-Daemon-6.05.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-lwp-mediatypes
    - perl-http-date
    - perl-http-message
    - perl-test-needs
    - perl-module-build-tiny
    - perl-uri
    #- perl-socket
    #- perl-sys-hostname
    #- perl-file-spec
    #- perl-strict
    #- perl-extutils-makemaker
    #- perl-warnings
    #- perl-carp
    #- perl-test
    #- perl-io-socket-ip
    #- perl-module-metadata
    #- perl-test-more

  run:
    - perl
    - perl-lwp-mediatypes
    - perl-http-date
    - perl-http-message
    #- perl-socket
    #- perl-strict
    #- perl-warnings
    #- perl-io-socket-ip
    #- perl-sys-hostname
    #- perl-carp

test:
  # Perl 'use' tests
  imports:
    - HTTP::Daemon

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/libwww-perl/HTTP-Daemon
  license: perl_5
  summary: 'A simple http server class'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: HTTP::Daemon
  cpan_module: HTTP::Daemon

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
