{% set name = "perl-try-tiny" %}
{% set version = "0.30" %}
{% set sha256 = "da5bd0d5c903519bbf10bb9ba0cb7bcac0563882bcfe4503aee3fb143eddef6b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Try-Tiny-0.30.tar.gz
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.30.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-constant
    #- perl-exporter
    #- perl-if
    #- perl-file-spec
    #- perl-strict
    #- perl-extutils-makemaker
    #- perl-warnings
    #- perl-carp
    #- perl-test-more

  run:
    - perl
    #- perl-constant
    #- perl-exporter
    #- perl-strict
    #- perl-warnings
    #- perl-carp

test:
  # Perl 'use' tests
  imports:
    - Try::Tiny

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/p5sagit/Try-Tiny
  license: mit
  summary: 'Minimal try/catch with proper preservation of $@'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Try::Tiny
  cpan_module: Try::Tiny

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
