{% set name = "perl-uri-escape" %}
{% set version = "1.76" %}
{% set sha256 = "b2c98e1d50d6f572483ee538a6f4ccc8d9185f91f0073fd8af7390898254413e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: URI-1.76.tar.gz
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-1.76.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/URI::Escape
  license: perl_5
  summary: 'Percent-encode and percent-decode unsafe characters'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: URI::Escape
  cpan_module: URI::Escape

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
