{% set name = "perl-pmtools" %}
{% set version = "2.2.0" %}
{% set sha256 = "2cc88d4408d5c3fcdd06de2ddb9e330b8fd55eb5450f89f8333f44b0b86bc7b8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: pmtools-2.2.0.tar.gz
  url: https://cpan.metacpan.org/authors/id/M/ML/MLFISHER/pmtools-2.2.0.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - pmtools

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/pmtools
  license: perl_5
  summary: 'Perl Module Tools'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: pmtools
  cpan_module: pmtools

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
