{% set name = "perl-doxygen-filter-perl" %}
{% set version = "1.72" %}
{% set sha256 = "235ca9283d0f6d662bf1a1b19561b0bc093c6479b3dbf76c3076367a69c91da5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Doxygen-Filter-Perl-1.72.tar.gz
  url: https://cpan.metacpan.org/authors/id/J/JO/JORDAN/Doxygen-Filter-Perl/Doxygen-Filter-Perl-1.72.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-pod-pom
    - perl-pod-pom-view-html
    - perl-test-output
    - perl-log-log4perl 1.46
    #- perl-extutils-makemaker
    #- perl-test-more

  run:
    - perl
    - perl-pod-pom
    - perl-pod-pom-view-html
    - perl-test-output
    - perl-log-log4perl 1.46
    #- perl-test-more

test:
  # Perl 'use' tests
  imports:
    - Doxygen::Filter
    - Doxygen::Filter::Perl
    - Doxygen::Filter::Perl::POD

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Doxygen::Filter::Perl
  license: unknown
  summary: 'Methods for pre-filtering Perl code for Doxygen'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Doxygen::Filter::Perl
  cpan_module: Doxygen::Filter::Perl

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
