{% set name = "perl-http-request" %}
{% set version = "6.18" %}
{% set sha256 = "d060d170d388b694c58c14f4d13ed908a2807f0e581146cef45726641d809112" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: HTTP-Message-6.18.tar.gz
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6.18.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/HTTP::Request
  license: perl_5
  summary: 'HTTP style request message'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: HTTP::Request
  cpan_module: HTTP::Request

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
