{% set name = "perl-ppix-utilities-node" %}
{% set version = "1.001000" %}
{% set sha256 = "03a483386fd6a2c808f09778d44db06b02c3140fb24ba4bf12f851f46d3bcb9b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: PPIx-Utilities-1.001000.tar.gz
  url: https://cpan.metacpan.org/authors/id/E/EL/ELLIOTJS/PPIx-Utilities-1.001000.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/PPIx::Utilities::Node
  license: perl_5
  summary: 'Extensions to PPI::Node.'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: PPIx::Utilities::Node
  cpan_module: PPIx::Utilities::Node

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
