{% set name = "perl-class-inspector" %}
{% set version = "1.36" %}
{% set sha256 = "cc295d23a472687c24489d58226ead23b9fdc2588e522f0b5f0747741700694e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Class-Inspector-1.36.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Class-Inspector-1.36.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-test-more
    #- perl-base

  run:
    - perl
    #- perl-file-spec
    #- perl-base

test:
  # Perl 'use' tests
  imports:
    - Class::Inspector
    - Class::Inspector::Functions

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://metacpan.org/pod/Class::Inspector
  license: perl_5
  summary: 'Get information about a class and its structure'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Class::Inspector
  cpan_module: Class::Inspector

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
