{% set name = "perl-cpanel-json-xs" %}
{% set version = "4.12" %}
{% set sha256 = "49417b118fb111607cc7d021443e5b32fd104c0bf59d1852c95923a4916ac658" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Cpanel-JSON-XS-4.12.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RU/RURBAN/Cpanel-JSON-XS-4.12.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-pod-text
    - {{ compiler('c') }}

  run:
    - perl
    #- perl-pod-text

test:
  # Perl 'use' tests
  imports:
    - Cpanel::JSON::XS
    - Cpanel::JSON::XS::Type

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Cpanel::JSON::XS
  license: perl_5
  summary: 'cPanel fork of JSON::XS, fast and correct serializing'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Cpanel::JSON::XS
  cpan_module: Cpanel::JSON::XS

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
