{% set name = "perl-lwp-useragent" %}
{% set version = "6.39" %}
{% set sha256 = "9a8d7747938aa75d7d524c71574ae7f99ca66a5dac8255a7f7759f373e7774d5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: libwww-perl-6.39.tar.gz
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.39.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/LWP::UserAgent
  license: perl_5
  summary: 'Web user agent class'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: LWP::UserAgent
  cpan_module: LWP::UserAgent

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
