{% set name = "perl-readonly" %}
{% set version = "2.05" %}
{% set sha256 = "4b23542491af010d44a5c7c861244738acc74ababae6b8838d354dfb19462b5e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Readonly-2.05.tar.gz
  url: https://cpan.metacpan.org/authors/id/S/SA/SANKO/Readonly-2.05.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-module-build-tiny
    #- perl-test-more

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Readonly
    - Readonly::Array
    - Readonly::Hash
    - Readonly::Scalar

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/sanko/readonly
  license: artistic_2
  summary: 'Facility for creating read-only scalars, arrays, hashes'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Readonly
  cpan_module: Readonly

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
