{% set name = "perl-http-cookies" %}
{% set version = "6.04" %}
{% set sha256 = "0cc7f079079dcad8293fea36875ef58dd1bfd75ce1a6c244cd73ed9523eb13d4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: HTTP-Cookies-6.04.tar.gz
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Cookies-6.04.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-http-date
    - perl-uri
    - perl-http-message
    #- perl-locale
    #- perl-vars
    #- perl-file-spec
    #- perl-strict
    #- perl-warnings
    #- perl-extutils-makemaker
    #- perl-carp
    #- perl-test
    #- perl-time-local
    #- perl-test-more

  run:
    - perl
    - perl-http-date
    - perl-http-message
    #- perl-locale
    #- perl-vars
    #- perl-strict
    #- perl-time-local
    #- perl-carp

test:
  # Perl 'use' tests
  imports:
    - HTTP::Cookies
    - HTTP::Cookies::Microsoft
    - HTTP::Cookies::Netscape

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/libwww-perl/http-cookies
  license: perl_5
  summary: 'HTTP cookie jars'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: HTTP::Cookies
  cpan_module: HTTP::Cookies

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
