{% set name = "perl-list-moreutils" %}
{% set version = "0.428" %}
{% set sha256 = "713e0945d5f16e62d81d5f3da2b6a7b14a4ce439f6d3a7de74df1fd166476cc2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: List-MoreUtils-0.428.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.428.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-list-moreutils-xs
    - perl-test-leaktrace
    - perl-exporter-tiny
    #- perl-extutils-makemaker
    #- perl-storable
    #- perl-test-more

  run:
    - perl
    - perl-list-moreutils-xs
    - perl-exporter-tiny

test:
  # Perl 'use' tests
  imports:
    - List::MoreUtils
    - List::MoreUtils::PP

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://metacpan.org/release/List-MoreUtils
  license: apache_2_0
  summary: 'Provide the stuff missing in List::Util'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: List::MoreUtils
  cpan_module: List::MoreUtils

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
