#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

set -xeuo pipefail
export PYTHONUNBUFFERED=1

cat >~/.condarc <<CONDARC
# Point to the internal Anaconda Enterprise repo
channel_alias: https://conda0.sarc.samsung.com/repository/conda

# explicitly configure default channels.  If/when we mirror either of these,
# we will need to update the defined default channels
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

# give Anaconda.org channels we will use in our channels list a short-name
# That way, if we choose to mirror those channels later, we can change the
# short name and have them
#
# custom_channels (map: str)
#   A map of key-value pairs where the key is a channel name and the value
#   is a channel location. Channels defined here override the default
#   'channel_alias' value. The channel name (key) is not included in the
#   channel location (value).  For example, to override the location of
#   the 'conda-forge' channel where the url to repodata is
#   https://anaconda-repo.dev/packages/conda-forge/linux-64/repodata.json,
#   add an entry 'conda-forge: https://anaconda-repo.dev/packages'.
#
custom_channels:
  conda-forge: https://conda.anaconda.org

# migrated_channel_aliases (sequence: str)
#   env var string delimiter: ','
#   A list of previously-used channel_alias values. Useful when switching
#   between different Anaconda Repository instances.
#
migrated_channel_aliases:
  - http://anaconda.spa.sarc.samsung.com/conda

# # migrated_custom_channels (map: str)
# #   A map of key-value pairs where the key is a channel name and the value
# #   is the previous location of the channel.
# #
# migrated_custom_channels: {}

channels:
#  - spa-overrides        # SPA team channel. contact tsnyder
  - conda-forge          # https://conda-forge.org/docs/user/introduction.html
  - defaults             # expands to default_channels configured above
#  - spa                  # SPA team channel. To be given membership for uploading packages, contact tsnyder
#  - anaconda-enterprise  # needed for anaconda-enterprise-cli


conda-build:
 root-dir: /home/conda/staged-recipes/build_artifacts

show_channel_urls: true

ssl_verify: /etc/pki/tls/cert.pem


CONDARC

conda config --show-sources

# Copy the host recipes folder so we don't ever muck with it
cp -r /home/conda/staged-recipes/recipes ~/conda-recipes
cp -r /home/conda/staged-recipes/.ci_support ~/.ci_support

# Find the recipes from master in this PR and remove them.
echo "Finding recipes merged in master and removing them from the build."
pushd /home/conda/staged-recipes/recipes > /dev/null
if [ "${AZURE}" == "True" ]; then
    git fetch --force origin master:master
fi
git ls-tree --name-only master -- . | xargs -I {} sh -c "rm -rf ~/conda-recipes/{} && echo Removing recipe: {}"
popd > /dev/null

# Unused, but needed by conda-build currently... :(
export CONDA_NPY='19'

# Make sure build_artifacts is a valid channel
conda index /home/conda/staged-recipes/build_artifacts

conda install --yes --quiet "conda!=4.6.1" conda-forge-ci-setup=2.* conda-forge-pinning networkx conda-build>=3.16
source run_conda_forge_build_setup

# yum installs anything from a "yum_requirements.txt" file that isn't a blank line or comment.
find ~/conda-recipes -mindepth 2 -maxdepth 2 -type f -name "yum_requirements.txt" \
    | xargs -n1 cat | { grep -v -e "^#" -e "^$" || test $? == 1; } | \
    xargs -r /usr/bin/sudo -n yum install -y

python ~/.ci_support/build_all.py ~/conda-recipes

cp -rf /home/conda/feedstock_root/build_artifacts/linux-64 /home/conda/staged-recipes/build_artifacts 

touch "/home/conda/staged-recipes/build_artifacts/conda-forge-build-done"
