{% set name = "perl-exception-class" %}
{% set version = "1.44" %}
{% set sha256 = "33f3fbf8b138d3b04ea4ec0ba83fb0df6ba898806bcf4ef393d4cafc1a23ee0d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Exception-Class-1.44.tar.gz
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.44.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-devel-stacktrace
    - perl-class-data-inheritable
    #- perl-base
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-overload
    #- perl-test-more
    #- perl-scalar-util
    #- perl-strict
    #- perl-warnings

  run:
    - perl
    - perl-devel-stacktrace
    - perl-class-data-inheritable
    #- perl-base
    #- perl-overload
    #- perl-scalar-util
    #- perl-strict
    #- perl-warnings

test:
  # Perl 'use' tests
  imports:
    - Exception::Class
    - Exception::Class::Base

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/release/Exception-Class
  license: perl_5
  summary: 'A module that allows you to declare real exception classes in Perl'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Exception::Class
  cpan_module: Exception::Class

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
