{% set name = "perl-www-robotrules" %}
{% set version = "6.02" %}
{% set sha256 = "46b502e7a288d559429891eeb5d979461dd3ecc6a5c491ead85d165b6e03a51e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: WWW-RobotRules-6.02.tar.gz
  url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/WWW-RobotRules-6.02.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-uri
    #- perl-fcntl
    #- perl-extutils-makemaker
    #- perl-anydbm_file

  run:
    - perl
    - perl-uri
    #- perl-fcntl
    #- perl-anydbm_file

test:
  # Perl 'use' tests
  imports:
    - WWW::RobotRules
    - WWW::RobotRules::AnyDBM_File
    - WWW::RobotRules::InCore

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/WWW::RobotRules
  license: perl_5
  summary: 'database of robots.txt-derived permissions'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: WWW::RobotRules
  cpan_module: WWW::RobotRules

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
