{% set name = "perl-pod-pom-view-html" %}
{% set version = "2.01" %}
{% set sha256 = "1b50fba9bbdde3ead192beeba0eaddd0c614e3afb1743fa6fff805f57c56f7f4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Pod-POM-2.01.tar.gz
  url: https://cpan.metacpan.org/authors/id/N/NE/NEILB/Pod-POM-2.01.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Pod::POM::View::HTML
  license: perl_5
  summary: 'create HTML views of POM objects'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Pod::POM::View::HTML
  cpan_module: Pod::POM::View::HTML

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
