{% set name = "perl-task-weaken" %}
{% set version = "1.06" %}
{% set sha256 = "2383fedb9dbaef646468ea824afbf7c801076720cfba0df2a7a074726dcd66be" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Task-Weaken-1.06.tar.gz
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Task-Weaken-1.06.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-test-more
    #- perl-scalar-util
    #- perl-config
    #- perl-strict
    #- perl-warnings
    #- perl-file-spec-functions

  run:
    - perl
    #- perl-strict

test:
  # Perl 'use' tests
  imports:
    - Task::Weaken

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/karenetheridge/Task-Weaken
  license: perl_5
  summary: 'Ensure that a platform has weaken support'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Task::Weaken
  cpan_module: Task::Weaken

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
