{% set name = "perl-module-build-tiny" %}
{% set version = "0.039" %}
{% set sha256 = "7d580ff6ace0cbe555bf36b86dc8ea232581530cbeaaea09bccb57b55797f11c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Module-Build-Tiny-0.039.tar.gz
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-extutils-helpers
    - perl-extutils-installpaths
    - perl-extutils-config
    #- perl-file-spec
    #- perl-io-file
    #- perl-data-dumper
    #- perl-file-path
    #- perl-exporter
    #- perl-warnings
    #- perl-extutils-cbuilder
    #- perl-io-handle
    #- perl-file-temp
    #- perl-pod-man
    #- perl-test-more
    #- perl-ipc-open3
    #- perl-file-spec-functions
    #- perl-blib
    #- perl-lib
    #- perl-getopt-long
    #- perl-strict
    #- perl-json-pp
    #- perl-carp
    #- perl-file-basename
    #- perl-extutils-install
    #- perl-dynaloader
    #- perl-cwd
    #- perl-extutils-parsexs
    #- perl-tap-harness-env
    #- perl-xsloader
    #- perl-file-find
    #- perl-cpan-meta
    #- perl-ipc-open2

  run:
    - perl
    - perl-extutils-helpers
    - perl-extutils-installpaths
    - perl-extutils-config
    #- perl-extutils-cbuilder
    #- perl-exporter
    #- perl-file-basename
    #- perl-extutils-install
    #- perl-dynaloader
    #- perl-cpan-meta
    #- perl-strict
    #- perl-extutils-parsexs
    #- perl-tap-harness-env
    #- perl-file-path
    #- perl-pod-man
    #- perl-getopt-long
    #- perl-file-find
    #- perl-json-pp
    #- perl-warnings
    #- perl-file-spec-functions

test:
  # Perl 'use' tests
  imports:
    - Module::Build::Tiny

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Module::Build::Tiny
  license: perl_5
  summary: 'A tiny replacement for Module::Build'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Module::Build::Tiny
  cpan_module: Module::Build::Tiny

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
