{% set name = "perl-yaml-xs" %}
{% set version = "0.79" %}
{% set sha256 = "8405bacd21758ca828064b401c55e549dd7bfdda834aa993101b032cdc989573" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: YAML-LibYAML-0.79.tar.gz
  url: https://cpan.metacpan.org/authors/id/T/TI/TINITA/YAML-LibYAML-0.79.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
  host:
    - perl
    - {{ compiler('c') }}

  run:
    - perl

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/YAML::XS
  license: perl_5
  summary: ''

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: YAML::XS
  cpan_module: YAML::XS

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
