{% set name = "perl-test-needs" %}
{% set version = "0.002006" %}
{% set sha256 = "77f9fff0c96c5e09f34d0416b3533c3319f7cd0bb1f7fe8f8072ad59f433f0e5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-Needs-0.002006.tar.gz
  url: https://cpan.metacpan.org/authors/id/H/HA/HAARG/Test-Needs-0.002006.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-test-more
    #- perl-extutils-makemaker

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Test::Needs

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Test::Needs
  license: perl_5
  summary: 'Skip tests when modules not available'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::Needs
  cpan_module: Test::Needs

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
