{% set name = "perl-lwp-protocol-https" %}
{% set version = "6.07" %}
{% set sha256 = "522cc946cf84a1776304a5737a54b8822ec9e79b264d0ba0722a70473dbfb9e7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: LWP-Protocol-https-6.07.tar.gz
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-6.07.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-net-https
    - perl-lwp-useragent
    - perl-test-requiresinternet
    - perl-io-socket-ssl
    - perl-mozilla-ca
    #- perl-extutils-makemaker
    #- perl-test-more

  run:
    - perl
    - perl-net-https
    - perl-lwp-useragent
    - perl-mozilla-ca
    - perl-io-socket-ssl

test:
  # Perl 'use' tests
  imports:
    - LWP::Protocol::https
    - LWP::Protocol::https::Socket

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/LWP::Protocol::https
  license: perl_5
  summary: 'Provide https support for LWP::UserAgent'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: LWP::Protocol::https
  cpan_module: LWP::Protocol::https

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
