{% set name = "perl-string-format" %}
{% set version = "1.18" %}
{% set sha256 = "9e417a8f8d9ea623beea2d13a47c0d5a696fc8602c0509b826cd45f97b76e778" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: String-Format-1.18.tar.gz
  url: https://cpan.metacpan.org/authors/id/S/SR/SREZIC/String-Format-1.18.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-test-more

  run:
    - perl
    #- perl-test-more

test:
  # Perl 'use' tests
  imports:
    - String::Format

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/String::Format
  license: unknown
  summary: 'sprintf-like string formatting capabilities with arbitrary format definitions'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: String::Format
  cpan_module: String::Format

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
