{% set name = "perl-http-negotiate" %}
{% set version = "6.01" %}
{% set sha256 = "1c729c1ea63100e878405cda7d66f9adfd3ed4f1d6cacaca0ee9152df728e016" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: HTTP-Negotiate-6.01.tar.gz
  url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Negotiate-6.01.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-http-headers
    #- perl-extutils-makemaker

  run:
    - perl
    - perl-http-headers

test:
  # Perl 'use' tests
  imports:
    - HTTP::Negotiate

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/HTTP::Negotiate
  license: perl_5
  summary: 'choose a variant to serve'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: HTTP::Negotiate
  cpan_module: HTTP::Negotiate

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
