{% set name = "perl-log-log4perl" %}
{% set version = "1.46" %}
{% set sha256 = "31011a17c04e78016e73eaa4865d0481d2ffc3dc22813c61065d90ad73c64e6f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Log-Log4perl-1.46.tar.gz
  url: https://cpan.metacpan.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.46.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-test-more
    #- perl-file-path

  run:
    - perl
    #- perl-file-spec
    #- perl-test-more
    #- perl-file-path

test:
  # Perl 'use' tests
  imports:
    - Log::Log4perl

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Log::Log4perl
  license: unknown
  summary: 'Log4j implementation for Perl'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Log::Log4perl
  cpan_module: Log::Log4perl

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
