{% set name = "perl-libwww-perl" %}
{% set version = "6.39" %}
{% set sha256 = "9a8d7747938aa75d7d524c71574ae7f99ca66a5dac8255a7f7759f373e7774d5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: libwww-perl-6.39.tar.gz
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.39.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-lwp-mediatypes
    - perl-http-date
    - perl-html-parser
    - perl-test-fatal
    - perl-http-message
    - perl-test-requiresinternet
    - perl-www-robotrules
    - perl-file-listing
    - perl-uri
    - perl-http-negotiate
    - perl-http-cookies
    - perl-encode-locale
    - perl-test-needs
    - perl-net-http
    - perl-http-daemon
    - perl-uri-escape
    - perl-try-tiny
    #- perl-io-socket
    #- perl-encode
    #- perl-file-copy
    #- perl-base
    #- perl-scalar-util
    #- perl-cpan-meta-requirements
    #- perl-mime-base64
    #- perl-digest-md5
    #- perl-findbin
    #- perl-file-spec
    #- perl-strict
    #- perl-extutils-makemaker
    #- perl-io-select
    #- perl-net-ftp
    #- perl-getopt-long
    #- perl-warnings
    #- perl-module-metadata
    #- perl-test-more

  run:
    - perl
    - perl-http-cookies
    - perl-http-date
    - perl-lwp-mediatypes
    - perl-html-parser
    - perl-encode-locale
    - perl-http-message
    - perl-net-http
    - perl-http-daemon
    - perl-www-robotrules
    - perl-file-listing
    - perl-uri
    - perl-http-negotiate
    - perl-uri-escape
    - perl-try-tiny
    #- perl-io-socket
    #- perl-encode
    #- perl-base
    #- perl-scalar-util
    #- perl-mime-base64
    #- perl-digest-md5
    #- perl-strict
    #- perl-io-select
    #- perl-net-ftp
    #- perl-warnings

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/libwww-perl/libwww-perl
  license: perl_5
  summary: 'The World-Wide Web library for Perl'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: libwww-perl
  cpan_module: libwww-perl

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
