{% set name = "perl-test-requiresinternet" %}
{% set version = "0.05" %}
{% set sha256 = "bba7b32a1cc0d58ce2ec20b200a7347c69631641e8cae8ff4567ad24ef1e833e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-RequiresInternet-0.05.tar.gz
  url: https://cpan.metacpan.org/authors/id/M/MA/MALLEN/Test-RequiresInternet-0.05.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-socket
    #- perl-test-more
    #- perl-strict
    #- perl-warnings

  run:
    - perl
    #- perl-socket
    #- perl-warnings
    #- perl-strict

test:
  # Perl 'use' tests
  imports:
    - Test::RequiresInternet

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://metacpan.org/dist/Test-RequiresInternet
  license: perl_5
  summary: 'Easily test network connectivity'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::RequiresInternet
  cpan_module: Test::RequiresInternet

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
