{% set name = "perl-test-without-module" %}
{% set version = "0.20" %}
{% set sha256 = "8e9aeb7c32a6c6d0b8a93114db2a8c072721273a9d9a2dd4f9ca86cfd28aa524" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-Without-Module-0.20.tar.gz
  url: https://cpan.metacpan.org/authors/id/C/CO/CORION/Test-Without-Module-0.20.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Test::Without::Module

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Test::Without::Module
  license: perl_5
  summary: 'Test fallback behaviour in absence of modules'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::Without::Module
  cpan_module: Test::Without::Module

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
