{% set name = "perl-test-deep" %}
{% set version = "1.128" %}
{% set sha256 = "852d7e836fba8269b0b755082051a24a1a309d015a8b76838790af9e3760092f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-Deep-1.128.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Deep-1.128.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-test-tester
    #- perl-test-more
    #- perl-scalar-util
    #- perl-test-builder
    #- perl-list-util

  run:
    - perl
    #- perl-test-builder
    #- perl-list-util
    #- perl-scalar-util

test:
  # Perl 'use' tests
  imports:
    - Test::Deep
    - Test::Deep::All
    - Test::Deep::Any
    - Test::Deep::Array
    - Test::Deep::ArrayEach
    - Test::Deep::ArrayElementsOnly
    - Test::Deep::ArrayLength
    - Test::Deep::ArrayLengthOnly
    - Test::Deep::Blessed
    - Test::Deep::Boolean
    - Test::Deep::Cache
    - Test::Deep::Cache::Simple
    - Test::Deep::Class
    - Test::Deep::Cmp
    - Test::Deep::Code
    - Test::Deep::Hash
    - Test::Deep::HashEach
    - Test::Deep::HashElements
    - Test::Deep::HashKeys
    - Test::Deep::HashKeysOnly
    - Test::Deep::Ignore
    - Test::Deep::Isa
    - Test::Deep::ListMethods
    - Test::Deep::MM
    - Test::Deep::Methods
    - Test::Deep::NoTest
    - Test::Deep::None
    - Test::Deep::Number
    - Test::Deep::Obj
    - Test::Deep::Ref
    - Test::Deep::RefType
    - Test::Deep::Regexp
    - Test::Deep::RegexpMatches
    - Test::Deep::RegexpOnly
    - Test::Deep::RegexpRef
    - Test::Deep::RegexpRefOnly
    - Test::Deep::RegexpVersion
    - Test::Deep::ScalarRef
    - Test::Deep::ScalarRefOnly
    - Test::Deep::Set
    - Test::Deep::Shallow
    - Test::Deep::Stack
    - Test::Deep::String
    - Test::Deep::SubHash
    - Test::Deep::SubHashElements
    - Test::Deep::SubHashKeys
    - Test::Deep::SubHashKeysOnly
    - Test::Deep::SuperHash
    - Test::Deep::SuperHashElements
    - Test::Deep::SuperHashKeys
    - Test::Deep::SuperHashKeysOnly

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://github.com/rjbs/Test-Deep/
  license: perl_5
  summary: 'Extremely flexible deep comparison'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::Deep
  cpan_module: Test::Deep

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
