{% set name = "perl-exporter-tiny" %}
{% set version = "1.002001" %}
{% set sha256 = "a82c334c02ce4b0f9ea77c67bf77738f76a9b8aa4bae5c7209d1c76453d3c48d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Exporter-Tiny-1.002001.tar.gz
  url: https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Exporter-Tiny-1.002001.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-test-more

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Exporter::Shiny
    - Exporter::Tiny

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://metacpan.org/release/Exporter-Tiny
  license: perl_5
  summary: 'an exporter with the features of Sub::Exporter but only core dependencies'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Exporter::Tiny
  cpan_module: Exporter::Tiny

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
