{% set name = "perl-file-which" %}
{% set version = "1.23" %}
{% set sha256 = "b79dc2244b2d97b6f27167fc3b7799ef61a179040f3abd76ce1e0a3b0bc4e078" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: File-Which-1.23.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Which-1.23.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-test-more

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - File::Which

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://metacpan.org/pod/File::Which
  license: perl_5
  summary: 'Perl implementation of the which utility as an API'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: File::Which
  cpan_module: File::Which

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
