{% set name = "perl-file-sharedir" %}
{% set version = "1.116" %}
{% set sha256 = "59d90bfdf98c4656ff4173e62954ea8cf0de66565e35d108ecd7050596cb8328" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: File-ShareDir-1.116.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RE/REHSACK/File-ShareDir-1.116.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-file-sharedir-install
    - perl-class-inspector
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-file-path
    #- perl-test-more
    #- perl-carp
    #- perl-warnings

  run:
    - perl
    - perl-class-inspector
    #- perl-file-spec
    #- perl-carp
    #- perl-warnings

test:
  # Perl 'use' tests
  imports:
    - File::ShareDir

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://metacpan.org/release/File-ShareDir
  license: perl_5
  summary: 'Locate per-dist and per-module shared files'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: File::ShareDir
  cpan_module: File::ShareDir

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
