{% set name = "perl-algorithm-diff" %}
{% set version = "1.1903" %}
{% set sha256 = "30e84ac4b31d40b66293f7b1221331c5a50561a39d580d85004d9c1fff991751" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Algorithm-Diff-1.1903.tar.gz
  url: https://cpan.metacpan.org/authors/id/T/TY/TYEMQ/Algorithm-Diff-1.1903.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Algorithm::Diff

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Algorithm::Diff
  license: unknown
  summary: "Compute `intelligent' differences between two files / lists but use the old (<=0.59) interface."

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Algorithm::Diff
  cpan_module: Algorithm::Diff

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
