{% set name = "perl-html-tagset" %}
{% set version = "3.20" %}
{% set sha256 = "adb17dac9e36cd011f5243881c9739417fd102fce760f8de4e9be4c7131108e2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: HTML-Tagset-3.20.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Tagset-3.20.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - HTML::Tagset

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/HTML::Tagset
  license: unknown
  summary: 'data tables useful in parsing HTML'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: HTML::Tagset
  cpan_module: HTML::Tagset

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
