{% set name = "perl-io-compress" %}
{% set version = "2.087" %}
{% set sha256 = "94f792775d0496fffe862363c76637e74ff5b46c40cf47042547686d164e23cb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: IO-Compress-2.087.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/IO-Compress-2.087.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-extutils-makemaker
    #- perl-scalar-util
    #- perl-compress-raw-bzip2
    #- perl-compress-raw-zlib

  run:
    - perl
    #- perl-compress-raw-zlib
    #- perl-scalar-util
    #- perl-compress-raw-bzip2

test:
  # Perl 'use' tests
  imports:
    - IO::Compress::Adapter::Bzip2
    - IO::Compress::Adapter::Deflate
    - IO::Compress::Adapter::Identity
    - IO::Compress::Base
    - IO::Compress::Base::Common
    - IO::Compress::Bzip2
    - IO::Compress::Deflate
    - IO::Compress::Gzip
    - IO::Compress::Gzip::Constants
    - IO::Compress::RawDeflate
    - IO::Compress::Zip
    - IO::Compress::Zip::Constants
    - IO::Compress::Zlib::Constants
    - IO::Compress::Zlib::Extra
    - IO::Uncompress::Adapter::Bunzip2
    - IO::Uncompress::Adapter::Identity
    - IO::Uncompress::Adapter::Inflate
    - IO::Uncompress::AnyInflate
    - IO::Uncompress::AnyUncompress
    - IO::Uncompress::Base
    - IO::Uncompress::Bunzip2
    - IO::Uncompress::Gunzip
    - IO::Uncompress::Inflate
    - IO::Uncompress::RawInflate
    - IO::Uncompress::Unzip

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/pmqs/IO-Compress
  license: perl_5
  summary: 'IO Interface to compressed data files/buffers'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: IO-Compress
  cpan_module: IO-Compress

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
