{% set name = "perl-text-diff" %}
{% set version = "1.45" %}
{% set sha256 = "e8baa07b1b3f53e00af3636898bbf73aec9a0ff38f94536ede1dbe96ef086f04" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Text-Diff-1.45.tar.gz
  url: https://cpan.metacpan.org/authors/id/N/NE/NEILB/Text-Diff-1.45.tar.gz
  sha256: {{ sha256 }}
  patches:
     - sublib_versions_not_in_sync.patch

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-algorithm-diff
    #- perl-exporter
    #- perl-extutils-makemaker

  run:
    - perl
    - perl-algorithm-diff
    #- perl-exporter

test:
  # Perl 'use' tests
  imports:
    - Text::Diff
    - Text::Diff::Config
    - Text::Diff::Table

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Text::Diff
  license: perl_5
  summary: 'Perform diffs on files and record sets'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Text::Diff
  cpan_module: Text::Diff

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
