{% set name = "perl-ppi-node" %}
{% set version = "1.270" %}
{% set sha256 = "622a698c781bb85d2bdf7bbfe040fe70d33b79774c9ae01fce2375dc73faf457" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: PPI-1.270.tar.gz
  url: https://cpan.metacpan.org/authors/id/M/MI/MITHALDU/PPI-1.270.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

# test:
  # Perl 'use' tests
  # imports:

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/PPI::Node
  license: perl_5
  summary: 'Abstract PPI Node class, an Element that can contain other Elements'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: PPI::Node
  cpan_module: PPI::Node

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
