{% set name = "perl-pod-markdown" %}
{% set version = "3.101" %}
{% set sha256 = "e8ff6b6c170576966adf20d4024e005f75dbe73242386a1d03600e1626e9f040" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Pod-Markdown-3.101.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RW/RWSTAUNER/Pod-Markdown-3.101.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-test-differences
    #- perl-pod-simple
    #- perl-file-spec
    #- perl-lib
    #- perl-pod-usage
    #- perl-getopt-long
    #- perl-encode
    #- perl-exporter
    #- perl-strict
    #- perl-warnings
    #- perl-pod-simple-methody
    #- perl-utf8
    #- perl-symbol
    #- perl-io-handle
    #- perl-file-temp
    #- perl-parent
    #- perl-extutils-makemaker
    #- perl-test-more
    #- perl-ipc-open3
    #- perl-file-spec-functions

  run:
    - perl
    #- perl-pod-simple-methody
    #- perl-pod-simple
    #- perl-parent
    #- perl-pod-usage
    #- perl-getopt-long
    #- perl-encode
    #- perl-strict
    #- perl-warnings

test:
  # Perl 'use' tests
  imports:
    - Pod::Markdown
    - Pod::Perldoc::ToMarkdown

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/rwstauner/Pod-Markdown
  license: perl_5
  summary: 'Convert POD to Markdown'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Pod::Markdown
  cpan_module: Pod::Markdown

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
