{% set name = "lastpass-cli" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lastpass/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b94f591627e06c9fed3bc38007b1adc6ea77127e17c7175c85d497096768671b

build:
  number: 0
  # Winders doesn't have asciidoc on conda-forge
  #script: "make && make install && make install-doc VERBOSE=1"  [not Win]
  #script: "make && make install"  [Win]
  # docs are failing. don't care enough to fix right now.
  script: "make && make install"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - asciidoc  [not Win]
    - libxml2   [not Win]
    - cmake
  host:
    - libcurl
    - libxml2
    - openssl
  run:
    - libcurl
    - libxml2
    - openssl

test:
  commands:
    - lpass -v

about:
  home: https://www.lastpass.com
  license: OpenSSL
  license_file: LICENSE.OpenSSL
  summary: 'LastPass command line interface tool'
  doc_url: https://lastpass.github.io/lastpass-cli/lpass.1.html
  dev_url: https://github.com/lastpass/lastpass-cli

extra:
  recipe-maintainers:
    - timsnyder
