{% set name = "perl-class-tiny" %}
{% set version = "1.006" %}
{% set sha256 = "2efcbd31528be51d3022c616768558b78c6172df5f03c5dc698939f65488cb4e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Class-Tiny-1.006.tar.gz
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.006.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-base
    #- perl-subs
    #- perl-strict
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-lib
    #- perl-test-more
    #- perl-exporter
    #- perl-carp
    #- perl-warnings

  run:
    - perl
    #- perl-carp
    #- perl-warnings
    #- perl-strict

test:
  # Perl 'use' tests
  imports:
    - Class::Tiny
    - Class::Tiny::Object

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/dagolden/Class-Tiny
  license: apache_2_0
  summary: 'Minimalist class construction'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Class::Tiny
  cpan_module: Class::Tiny

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
