{% set name = "perl-test-differences" %}
{% set version = "0.67" %}
{% set sha256 = "c88dbbb48b934b069284874f33abbaaa438aa31204aa3fa73bfc2f4aeac878da" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-Differences-0.67.tar.gz
  url: https://cpan.metacpan.org/authors/id/D/DC/DCANTRELL/Test-Differences-0.67.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-capture-tiny
    - perl-text-diff
    #- perl-test-more
    #- perl-extutils-makemaker
    #- perl-data-dumper

  run:
    - perl
    - perl-capture-tiny
    - perl-text-diff
    #- perl-data-dumper
    #- perl-test-more

test:
  # Perl 'use' tests
  imports:
    - Test::Differences

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Test::Differences
  license: unknown
  summary: 'Test strings and data structures and show differences if not ok'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::Differences
  cpan_module: Test::Differences

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
