{% set name = "perl-pod-spell" %}
{% set version = "1.20" %}
{% set sha256 = "6383f7bfe22bc0d839a08057a0ce780698b046184aea935be4833d94986dd03c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Pod-Spell-1.20.tar.gz
  url: https://cpan.metacpan.org/authors/id/D/DO/DOLMEN/Pod-Spell-1.20.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    - perl-lingua-en-inflect
    - perl-file-sharedir
    - perl-file-sharedir-install
    - perl-class-tiny
    - perl-test-deep
    - perl-path-tiny
    #- perl-locale
    #- perl-file-spec
    #- perl-posix
    #- perl-carp
    #- perl-strict
    #- perl-warnings
    #- perl-utf8
    #- perl-pod-escapes
    #- perl-text-wrap
    #- perl-io-handle
    #- perl-file-temp
    #- perl-parent
    #- perl-extutils-makemaker
    #- perl-pod-parser
    #- perl-test-more
    #- perl-ipc-open3
    #- perl-constant

  run:
    - perl
    - perl-lingua-en-inflect
    - perl-file-sharedir
    - perl-class-tiny
    - perl-path-tiny
    #- perl-pod-escapes
    #- perl-carp
    #- perl-locale
    #- perl-text-wrap
    #- perl-parent
    #- perl-pod-parser
    #- perl-posix
    #- perl-strict
    #- perl-warnings
    #- perl-constant

test:
  # Perl 'use' tests
  imports:
    - Pod::Spell
    - Pod::Wordlist

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/perl-pod/Pod-Spell
  license: artistic_2
  summary: 'a formatter for spellchecking Pod'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Pod::Spell
  cpan_module: Pod::Spell

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
