{% set name = "perl-test-nowarnings" %}
{% set version = "1.04" %}
{% set sha256 = "638a57658cb119af1fe5b15e73d47c2544dcfef84af0c6b1b2e97f08202b686c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Test-NoWarnings-1.04.tar.gz
  url: https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Test-NoWarnings-1.04.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-test-builder
    #- perl-test-tester
    #- perl-test-more
    #- perl-extutils-makemaker

  run:
    - perl
    #- perl-test-builder

test:
  # Perl 'use' tests
  imports:
    - Test::NoWarnings
    - Test::NoWarnings::Warning

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Test::NoWarnings
  license: open_source
  summary: "Make sure you didn't emit any warnings while testing"

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Test::NoWarnings
  cpan_module: Test::NoWarnings

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
