{% set name = "perl-extutils-config" %}
{% set version = "0.008" %}
{% set sha256 = "ae5104f634650dce8a79b7ed13fb59d67a39c213a6776cfdaa3ee749e62f1a8c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: ExtUtils-Config-0.008.tar.gz
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
    #- perl-io-handle
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-test-more
    #- perl-warnings
    #- perl-data-dumper
    #- perl-strict
    #- perl-ipc-open3

  run:
    - perl
    #- perl-strict
    #- perl-warnings
    #- perl-data-dumper

test:
  # Perl 'use' tests
  imports:
    - ExtUtils::Config

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/ExtUtils::Config
  license: perl_5
  summary: "A wrapper for perl's configuration"

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: ExtUtils::Config
  cpan_module: ExtUtils::Config

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
