{% set name = "perl-compress-raw-lzma" %}
{% set version = "2.087" %}
{% set sha256 = "256c076f16538d07c109a3d37a96cf1154d2d1c215e85e81c4ee90ea19557568" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Compress-Raw-Lzma-2.087.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Lzma-2.087.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
  host:
    - perl
    #- perl-extutils-makemaker
    - {{ compiler('c') }}

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Compress::Raw::Lzma

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/pmqs/Compress-Raw-Lzma
  license: perl_5
  summary: 'Low-Level Interface to lzma compression library'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Compress::Raw::Lzma
  cpan_module: Compress::Raw::Lzma

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
