{% set name = "perl-compress-raw-lzma" %}
{% set version = "2.074" %}
{% set sha256 = "d48aae8c79c9178be6e9c887b9e264fa61d7119bfebccdb0c243ab9af392381c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Lzma-2.074.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
  host:
    - perl
    #- perl-extutils-makemaker
    - {{ compiler('c') }}
    - xz

  run:
    - perl
    - xz

test:
  # Perl 'use' tests
  imports:
    - Compress::Raw::Lzma

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/pmqs/Compress-Raw-Lzma
  license: perl_5
  summary: 'Low-Level Interface to lzma compression library'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: Compress::Raw::Lzma
  cpan_module: Compress::Raw::Lzma

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
