{% set name = "perl-io-string" %}
{% set version = "1.08" %}
{% set sha256 = "2a3f4ad8442d9070780e58ef43722d19d1ee21a803bf7c8206877a10482de5a0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: IO-String-1.08.tar.gz
  url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/IO-String-1.08.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - IO::String

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/IO::String
  license: unknown
  summary: 'Emulate file interface for in-core strings'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: IO::String
  cpan_module: IO::String

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
