{% set name = "perl-b-cow" %}
{% set version = "0.001" %}
{% set sha256 = "8d5c3dfe09bbc9100cc56635816d0758c1b32777122246ef652661712a74b0d8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: B-COW-0.001.tar.gz
  url: https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/B-COW-0.001.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
  host:
    - perl
    #- perl-devel-peek
    #- perl-file-spec
    #- perl-extutils-makemaker
    #- perl-test-more
    - {{ compiler('c') }}

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - B::COW

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/B::COW
  license: perl_5
  summary: 'B::COW additional B helpers to check COW status'

extra:
  # these store the original arguments conda-skeleton was run with
  cpan_distribution: B::COW
  cpan_module: B::COW

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
